/* Generated by tools/decomp2proj.py - do not edit.
 *
 * Unrecovered register state. Each of these is a place where the
 * decompiler knew a value existed but not where it came from, so
 * nothing here carries meaning at runtime - treat any function that
 * reads one as not yet fully reversed.
 */

#ifndef FW_ARTIFACTS_H
#define FW_ARTIFACTS_H

extern int _local_10;
extern int stack0x00000010;
extern int stack0xffffffb5;
extern int stack0xffffffb6;
extern int stack0xffffffb7;
extern int stack0xffffffe0;
extern int stack0xfffffff1;
extern int unaff_fp;
extern int unaff_r4;
extern int unaff_r5;
extern int unaff_r6;
extern int unaff_r7;
extern int unaff_r8;
extern int unaff_r9;
extern int unaff_sl;

#endif /* FW_ARTIFACTS_H */
